# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20170223_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='added_ad',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='added_ad',
            new_name='added_at',
        ),
    ]
