# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20170224_0706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionManager',
        ),
    ]
